#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
# Fixed version: the previous script embedded literal double-quote
# characters inside DEFAULT_JVM_OPTS and then word-split it unquoted,
# which made the shell pass literal `"-Xmx64m"` (quotes included) as a
# single malformed token to `java`, causing it to be misinterpreted as a
# class name and fail immediately. This version avoids embedding quotes
# in the variable and does not rely on word-splitting a quoted string.
##############################################################################

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

APP_HOME=$(cd "$(dirname "$0")" >/dev/null && pwd)
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    echo "ERROR: gradle-wrapper.jar not found at $CLASSPATH" >&2
    echo "This repo does not vendor the wrapper jar (binary file, could not" >&2
    echo "be fetched in the offline environment this project was built in)." >&2
    echo "CI regenerates it automatically (see .github/workflows/build-apk.yml)." >&2
    echo "For a local build, run: gradle wrapper --gradle-version 8.9" >&2
    exit 1
fi

# Determine the Java command.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ]; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found on PATH." >&2
        exit 1
    fi
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
